version: '2'

networks:
    default:
        external:
            name: w-ros_default
            
services:

    db:
      image: mariadb
      container_name: lamp_mariadb
      restart: unless-stopped
#    volumes:
#      - "./db:/var/lib/mysql:rw"
      environment:
          - MYSQL_ROOT_PASSWORD=123456

    web:
      build: .
      image: wn1980/web-server
      container_name: lamp_php_apache
      depends_on:
          - db
      restart: unless-stopped
      volumes:
          - "./html/:/var/www/html:rw"
      ports:
          - "80:80"
          
    adminer:
      image: adminer
      container_name: lamp_adminer
      depends_on:
          - db
      restart: unless-stopped
      ports:
          - "8080:8080"
