version: '2'

services:

  php:
    build: .
    image: wn1980/web-server
    container_name: lamp_php7_apache
    restart: unless-stopped
    volumes:
      - "./html/:/var/www/html:rw"
    ports:
      - "80:80"

  db:
    image: mariadb
    container_name: lamp_mariadb
    restart: unless-stopped
#    volumes:
#      - "./db:/var/lib/mysql:rw"
    environment:
      - MYSQL_ROOT_PASSWORD=123456

  adminer:
      image: adminer
      container_name: lamp_adminer
      restart: always
      ports:
        - "8080:8080"
